### ISSUE TITLE
Terminal Id Error

### ISSUE THREAD

**Issue by hitaspdotnet** [kharazian/Nop.Plugin.Payments.MellatBank#1]
سلام دوست عزیز
ممنون بابت اشتراک گذاری
متاسفانه نتونستم نصب کنم
اولین ایرادش ترمینال ایدی رو Bool معرفی کردین که همین باعث میشه توی ادمین ویو بصورت چک اکس بیاد
دوم اینکه بعد از زدن کلید پرداخت محصول به لیست سفارشا اضافه میشه بدون اینکه پرداختی صورت بگیره و اصلا به درگاه بانک نمیره

**Comment by kharazian** [comment]
The error has been removed. Furthermore transaction list added for checking transaction state.
release [3.90](https://github.com/kharazian/Nop.Plugin.Payments.MellatBank/tree/3.90)
![list](https://user-images.githubusercontent.com/7446990/38347614-affd8670-38b1-11e8-81f9-8da41f4952af.jpg)
